import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import NavBar from "@/components/shared/nav-bar";
import Footer from "@/components/shared/footer";
import { FlickeringGrid } from "@/components/ui/flickering-grid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const satoshi = localFont({
  src: "fonts/fonts/Satoshi-Variable.ttf", 
  variable: "--font-satoshi",
  display: "swap", 
});

const clash = localFont({
  src: "fonts/fonts/ClashDisplay-Regular.ttf",
  variable: "--font-clash",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} ${clash.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col">
            <FlickeringGrid
              className=" -z-10 absolute inset-0 size-full"
              squareSize={4}
              gridGap={20}
              color="#6B7280"
              maxOpacity={0.2}
              flickerChance={0.1}
            />
            <NavBar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
